In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from os import listdir

In [2]:
from keras.preprocessing import sequence
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Flatten
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
from keras import optimizers
from keras.regularizers import l1,l2,l1_l2

from keras.optimizers import Adam
from keras.models import load_model
from keras.callbacks import ModelCheckpoint

Using TensorFlow backend.


In [3]:
df = pd.read_csv('df_train.csv')
df

5160399000.0  5160532000.0  5160665000.0  5160798000.0  5160931000.0  \
0          7.172340     13.318998     15.115269     12.120115     12.898385   
1          8.772359     11.914471     14.203160     11.378137     11.834629   
2          8.391178     11.156736     14.503078     12.438627     12.427057   
3          6.163323     10.432897     15.272127     13.891915     12.910382   
4          8.363369     11.315283     14.668475     13.853479     13.341522   
5          8.240896     13.739551     16.909309     15.751151     14.918041   
6          8.199476     14.391475     16.913791     14.984069     15.889930   
7          8.853883     14.978434     16.108675     14.508603     16.282452   
8         11.864605     14.443004     15.056640     13.854646     16.628577   
9         12.044046     13.901843     14.996692     13.340502     15.901869   
10        12.000502     11.161174     12.304590     10.981945     14.020130   
11        11.009739      6.696167      8.851695      8.604338      9.831945   
12        10.710425      6.472041      8.870798      9.353898     10.045588   
13        11.119380      6.480221      9.357864      9.437663     10.433410   
14        11.274165      9.157544     12.527337     12.544984     13.128968   
15        12.009174      9.487551     12.104957     12.625189     14.399263   
16         9.538186     12.054952     15.916731     16.364508     16.908687   
17         9.679094     10.130663     12.789477     12.697033     14.169171   
18         9.747741      9.266228     12.325115     12.962559     14.420597   
19         7.439547      9.638238     11.260506     12.691266     15.825068   
20         4.274476     10.438699     11.532323     13.213612     15.792665   
21         6.887031     10.656030     11.362563     12.907802     15.365951   
22         4.436359     12.480917     13.446605     16.219327     19.183547   
23         4.118565     10.208285     10.536491     13.800593     16.140542   
24         6.914918     10.985562     12.724060     14.566079     15.455448   
25         9.380944     10.739263     13.467298     13.836697     14.683016   
26         9.306278     11.114056     13.504390     14.234118     15.028142   
27        11.921901      8.441833     11.472655     11.100217     11.098933   
28        11.246917     10.327934     13.314400     12.926586     13.316439   
29        10.827744      9.311295     11.597787     11.482360     11.850252   
...             ...           ...           ...           ...           ...   
15180     36.992013     39.912650     43.395332     41.524123     42.187007   
15181     37.163290     39.970485     43.377267     41.563883     42.055915   
15182     37.393829     40.072165     43.468229     42.053663     41.743654   
15183     37.211863     40.486357     43.243457     42.037566     41.391569   
15184     37.456234     40.471355     43.610289     41.750952     41.538620   
15185     37.614923     40.722697     43.304040     42.033797     41.307115   
15186     37.059418     40.596976     43.170544     42.011063     41.398246   
15187     36.225299     39.879450     42.818162     41.775259     41.757766   
15188     35.953910     39.760255     43.129979     41.116195     41.817864   
15189     35.900106     39.796715     43.101024     41.245262     41.710272   
15190     36.278977     39.611590     43.267490     41.271954     41.788141   
15191     36.477841     39.606372     43.360845     41.202470     41.593668   
15192     36.626927     39.476846     43.264423     41.164471     41.344371   
15193     36.824964     39.450795     43.342875     41.765245     41.388499   
15194     36.630393     38.539128     42.607177     41.875940     41.411966   
15195     36.448525     38.617766     42.663254     41.643979     41.688820   
15196     36.733152     39.367961     43.237137     41.644725     41.686894   
15197     36.872762     39.384064     43.141080     41.305395     41.712731   
15198     37.125380     38.667390     43.421459     41.48

In [4]:
# df.loc[df['target'] <= 5, 'target'] = 0
# df.loc[(df['target'] <= 11) & (df['target'] > 5), 'target'] = 1
# df.loc[df['target'] > 11, 'target'] = 2

In [5]:
df = df.T
df

0          1          2          3          4      \
5160399000.0   7.172340   8.772359   8.391178   6.163323   8.363369   
5160532000.0  13.318998  11.914471  11.156736  10.432897  11.315283   
5160665000.0  15.115269  14.203160  14.503078  15.272127  14.668475   
5160798000.0  12.120115  11.378137  12.438627  13.891915  13.853479   
5160931000.0  12.898385  11.834629  12.427057  12.910382  13.341522   
5161064000.0  13.807718  12.236748  13.169839   9.931044  10.920540   
5161197000.0  15.543046  14.267263  14.929343  12.755279  13.074407   
5161330000.0  14.583542  14.501087  14.835480  12.925886  12.922540   
5161463000.0  11.757287  11.912227  12.524612  12.226484  11.044026   
5161596000.0  12.031413  11.376563  12.274352  13.552130  13.024234   
5161729000.0  12.772845  12.280226  13.351985  13.027066  12.055435   
5161862000.0  12.781531  11.878855  11.455238  11.803574  10.601036   
5161995000.0  11.091299  10.355700  10.282785  10.029090   8.817445   
5162128000.0  11.087194  10.323215   9.138612   7.919606   7.468650   
5162261000.0  10.323867   9.680516   8.818670   8.109822  10.134310   
5162394000.0   9.972357  10.231913  11.110409  10.621072  12.598702   
5162527000.0  10.611108   9.790839  10.377118   9.989393  12.318545   
5162660000.0   8.922171   8.214898   9.209779   9.664166  10.991813   
5162793000.0  10.441022  10.248179   9.796487   9.295672   9.795942   
5162926000.0  11.812957  11.829244  12.069642  10.329280  11.098698   
5163059000.0  14.607259  14.271379  14.544831  13.889937  13.975727   
5163192000.0  15.347494  13.943575  14.883477  13.582630  13.619151   
5163325000.0  15.291546  13.324038  13.195065  12.617758  14.328698   
5163458000.0  15.383821  13.981960  13.665742  14.563905  15.164730   
5163591000.0  17.121176  15.521436  16.315275  17.896439  17.883451   
5163724000.0  16.994598  15.468448  16.604356  18.646803  18.952407   
5163857000.0  17.111848  16.045966  16.565793  17.665812  17.895572   
5163990000.0  15.896414  13.870767  13.978961  15.673994  15.965597   
5164123000.0  14.563588  13.180264  14.601769  16.503956  16.994315   
5164256000.0  12.880515  12.199683  12.750908  13.911788  14.975316   
...                 ...        ...        ...        ...        ...   
5175694000.0  17.055987  15.276923  15.399025  15.024551  15.997048   
5175827000.0  18.570771  17.333314  16.994020  15.185738  15.046615   
5175960000.0  15.564189  13.752311  13.702489  14.849781  15.472335   
5176093000.0  16.221404  14.407768  14.027421  16.600957  17.245984   
5176226000.0  19.929742  17.987157  17.859417  19.487177  18.810344   
5176359000.0  17.591655  16.364035  16.299868  18.429847  18.208521   
5176492000.0  17.172551  15.241703  16.200596  16.527870  16.810449   
5176625000.0  18.019314  16.202751  16.055637  13.784727  14.335866   
5176758000.0  15.335702  13.830007  14.006218  13.029220  13.989088   
5176891000.0  14.406353  14.094454  14.118115  14.646343  14.805313   
5177024000.0  13.043179  13.478494  12.723542  14.175209  14.583071   
5177157000.0  12.848160  12.599535  13.734321  14.244729  13.509664   
5177290000.0  12.708656  12.176787  13.128644  12.216075  12.591372   
5177423000.0  14.077447  13.552216  13.774322  12.782356  11.290751   
5177556000.0  13.504877  12.938194  13.759141  14.028128  12.279086   
5177689000.0  11.871519  10.717781  12.087863  12.885159  12.264678   
5177822000.0  10.946026  11.046977  11.102249  11.231852  11.348238   
5177955000.0   9.893353  10.050732  10.982574  11.745010  12.420347   
5178088000.0  10.366398  10.718675  11.308807  12.471096  12.215028   
5178221000.0  12.648630  12.186594  11.918748  11.888408  11.817469   
5178354000.0  12.937673  11.545565  11.538292  11.433129  11.894255   
5178487000.0  12.112266  10.424321  10.504514  11.008790  11.838393   
5178620000.0  15.071740  13.245390  12.372451  13.047578  13.996025   
5178753000.0  15.653405  13.355729  12.029099  12.179321  13.175538   
5178886000.0  15.110099  12.802243  12.614

In [6]:
sequences = list()
for i in range(df.shape[1]):
    values = df.iloc[:-1,i].values
    sequences.append(values)
targets = df.iloc[-1, :].values

In [7]:
len(sequences)

15210

In [8]:
sequences[0]

array([ 7.17234047, 13.31899781, 15.11526853, 12.12011535, 12.89838533,
       13.80771827, 15.5430457 , 14.58354249, 11.75728735, 12.03141335,
       12.77284521, 12.78153054, 11.09129892, 11.08719423, 10.32386674,
        9.97235726, 10.61110839,  8.92217133, 10.44102193, 11.81295697,
       14.60725906, 15.34749356, 15.29154604, 15.38382071, 17.12117606,
       16.99459822, 17.11184767, 15.89641411, 14.563588  , 12.88051489,
       14.13096786, 14.99422852, 12.39221563, 12.39080188, 10.19337126,
       10.75794911, 13.28910346, 12.5761107 , 12.5176845 , 14.38461933,
       12.72646239, 12.57594704, 14.99343339, 15.00171095, 16.04131217,
       16.06152557, 16.73092476, 17.69384976, 17.77854092, 17.82542784,
       17.07003689, 16.89298112, 16.78195861, 16.69825677, 16.77953904,
       16.20400008, 15.4376026 , 14.31727986, 13.06644462, 12.44507043,
       11.87834992,  9.6339479 ,  9.98000108, 10.6455822 , 10.99836535,
       11.24450944, 11.44267255, 12.73587437, 14.39489327, 16.92

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from keras.utils import np_utils
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(targets)
encoded_y = encoder.transform(targets)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_y)
dummy_y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [10]:
targets = dummy_y

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, y_train = sequences, targets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.08, random_state=1)

In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.externals.joblib import dump, load
# sc = StandardScaler()
sc = load('std_scaler_smooth.bin')
X_train = sc.transform(X_train)
# X_test = sc.transform(X_test)
X_val = sc.transform(X_val)
# sc = MinMaxScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

X_train, X_val

/home/hongyu/anaconda3/envs/keras/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


(array([[ 0.01690185, -0.20545567, -0.24419498, ..., -0.22409581,
         -0.36910096, -0.31737886],
        [ 1.3384339 ,  0.53213175,  0.44717281, ...,  0.61856453,
          0.58925628,  0.62409537],
        [ 1.35589617,  1.38247085,  1.46816656, ...,  1.30835327,
          1.35014508,  1.42462305],
        ...,
        [-0.26756809,  0.16628436,  0.07638509, ...,  0.05777043,
          0.19842118,  0.07414391],
        [-0.71466385, -0.58890761, -0.74438187, ..., -0.73080378,
         -0.811521  , -0.78288819],
        [ 0.66072923,  0.6532634 ,  0.65688728, ...,  0.70261889,
          0.64700206,  0.71254075]]),
 array([[-0.02986961,  0.01183467,  0.09033338, ...,  0.02016512,
          0.0484155 ,  0.0589722 ],
        [ 0.47420165,  0.52526126,  0.58918153, ...,  0.47453451,
          0.5152193 ,  0.52026648],
        [-0.60141307, -0.60363401, -0.54388274, ..., -0.66594202,
         -0.63882365, -0.62722956],
        ...,
        [-0.67633589, -0.77502777, -0.77948015, ..., -

In [13]:
X_train.shape, X_val.shape

((13993, 144), (1217, 144))

In [14]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
# X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_val = np.reshape(X_val, (X_val.shape[0], X_val.shape[1], 1))

In [15]:
X_train.shape, X_val.shape

((13993, 144, 1), (1217, 144, 1))

In [20]:
model = Sequential()
model.add(LSTM(144, return_sequences=True, input_shape=(144, 1), kernel_regularizer=l2(0.01)))
# , kernel_regularizer=l2(0.01), recurrent_regularizer=l2(0.01), bias_regularizer=l2(0.01)
# model.add(LSTM(128, dropout = 0.2, recurrent_dropout = 0.2, input_shape=(12, 1),return_sequences=False))
model.add(Dropout(0.3))
# model.add(LSTM(72, dropout = 0.2, return_sequences=False, kernel_regularizer=l2(0.01), recurrent_regularizer=l2(0.01), bias_regularizer=l2(0.01)))
# model.add(Dropout(0.1))
# model.add(LSTM(64))
# model.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu'))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(18, activation='softmax'))
# adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, amsgrad=False)
# model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# monitor = EarlyStopping(monitor = 'val_loss', min_delta = 1e-3, patience = 5, verbose = 1, mode = 'auto')

In [21]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 144, 144)          84096     
_________________________________________________________________
dropout_2 (Dropout)          (None, 144, 144)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 20736)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 100)               2073700   
_________________________________________________________________
dense_3 (Dense)              (None, 18)                1818      
Total params: 2,159,614
Trainable params: 2,159,614
Non-trainable params: 0
_________________________________________________________________


In [24]:
import os
model_filename = 'model-{epoch:03d}-{acc:03f}-{val_acc:03f}-{val_loss:03f}.h5'
checkpoint_path = os.path.join('temp_lstm_smoothOnly/', model_filename)
monitor = EarlyStopping(monitor = 'val_loss', min_delta = 1e-3, patience = 10, verbose = 1, mode = 'auto')
checkpoint = ModelCheckpoint(filepath=checkpoint_path, verbose=1, monitor='val_loss',save_best_only=True, mode='auto')  
adam = optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, amsgrad=False)
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [25]:
# Fitting our model 
print('Train...')
history = model.fit(X_train, y_train, validation_data = (X_val, y_val), callbacks = [monitor, checkpoint], verbose = 1, batch_size = 128, nb_epoch = 100)

Train...
Train on 13993 samples, validate on 1217 samples
Epoch 1/100
13993/13993 [==============================] - 18s 1ms/step - loss: 0.1491 - acc: 0.9541 - val_loss: 0.3500 - val_acc: 0.8809

Epoch 00001: val_loss improved from inf to 0.35002, saving model to temp_lstm_smoothOnly/model-001-0.954120-0.880855-0.350018.h5
Epoch 2/100
13993/13993 [==============================] - 18s 1ms/step - loss: 0.1260 - acc: 0.9606 - val_loss: 0.3560 - val_acc: 0.8825

Epoch 00002: val_loss did not improve
Epoch 3/100
13993/13993 [==============================] - 19s 1ms/step - loss: 0.1285 - acc: 0.9623 - val_loss: 0.2992 - val_acc: 0.9047

Epoch 00003: val_loss improved from 0.35002 to 0.29924, saving model to temp_lstm_smoothOnly/model-003-0.962267-0.904684-0.299244.h5
Epoch 4/100
13993/13993 [==============================] - 18s 1ms/step - loss: 0.1342 - acc: 0.9588 - val_loss: 0.3605 - val_acc: 0.8833

Epoch 00004: val_loss did not improve
Epoch 5/100
13993/13993 [=======================

In [ ]:
# serialize model to JSON
model_json = model.to_json()
with open("/home/hongyu/Documents/Spring2020/ECE_research/signal_analysis/data_18points/3_section_sliding5/MSLSTM_models/LSTM_18pts_smoothOnly.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
# model.save_weights("/home/hongyu/Documents/Spring2020/ECE_research/signal_analysis/data_18points/3_section_sliding/weights_mixed/LSTM3sec_weight.h5")
print("Saved model to disk")

In [5]:
from keras.models import model_from_json
# load json and create model
json_file = open("/home/hongyu/Documents/Spring2020/ECE_research/signal_analysis/data_18points/3_section_sliding5/MSLSTM_models/LSTM_18pts_smoothOnly.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
# load weights into new model
# model.load_weights("/home/hongyu/Documents/Spring2020/ECE_research/3_section/weights_mixed/LSTM3sec_weight.h5")
print("Loaded model from disk")

Loaded model from disk
